version: '3'

volumes:
  es_data:
  es_logs:

services:
  # Define Logstash Dockerfile relative location, Docker image and ports 
  logstash: 
    build: ./logstash
    restart: always
    image: logstash:7.7.1
    ports:
    - "5000:5000/tcp"
    - "9600:9600/tcp"
    - "5000:5000/udp"

 # Define Elastic Search Dockerfile relative location, Docker image and ports 
  elasticsearch:
    build: ./elasticsearch
    restart: always
    image: elasticsearch:7.7.1
    ports:
    - "9300:9300/tcp"
    - "9200:9200/tcp"
    
    # Define persistent volumes 
    # These are nessessary to keep Elastic Stack data, logs and configuration persistent during destructions and rebuild of the stack
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
  
  # Define Logstash Dockerfile relative location, Docker image and ports 
  kibana:
    build: ./kibana
    restart: always
    image: kibana:7.7.1
    ports:
    - "5601:5601/tcp"
