version: '3'
services:
  logstash:
    build: ./logstash
    image: logstash:latest
    ports:
    - "5000:5000/tcp"
    - "9600:9600/tcp"
    - "5000:5000/udp"

  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch:latest
    ports:
    - "9300:9300/tcp"
    - "9200:9200/tcp"
    volumes:
      - ~/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/elasticsearch/logs:/usr/share/elasticsearch/logs
    
  kibana:
    build: ./kibana
    image: kibana:latest
    ports:
    - "5601:5601/tcp"