version: '3'
services:
  # Define Logstash Dockerfile relative location, Docker image and ports 
  logstash: 
    build: ./logstash
    image: logstash:latest
    ports:
    - "5000:5000/tcp"
    - "9600:9600/tcp"
    - "5000:5000/udp"

 # Define Elastic Search Dockerfile relative location, Docker image and ports 
  elasticsearch:
    build: ./elasticsearch
    image: elasticsearch:latest
    ports:
    - "9300:9300/tcp"
    - "9200:9200/tcp"
    
    # Define persisten volumes 
    # These are nessessary to keep Elastic Stack data, logs and configuration persistent during destructions and rebuild of the stack
    volumes:
      - ~/elasticsearch/data:/usr/share/elasticsearch/data
      - ~/elasticsearch/logs:/usr/share/elasticsearch/logs
  
  # Define Logstash Dockerfile relative location, Docker image and ports 
  kibana:
    build: ./kibana
    image: kibana:latest
    ports:
    - "5601:5601/tcp"